# docker-compose.yml

version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    # Esta linha carrega todas as variáveis do arquivo .env
    env_file:
      - ./.env
    restart: unless-stopped

  # ... serviço frontend